/// Immutable document blocks.
///
/// Token-position provenance: a block's [Block.size] is its content length
/// plus 2 because every block contributes an opening and a closing token,
/// exactly as in ProseMirror. Design follows prosemirror-model's node size
/// semantics (`src/node.ts`, https://github.com/ProseMirror/prosemirror-model,
/// MIT; repository archived April 2026). Design reference only — no source
/// code was copied.
library;

import 'attributes.dart';
import 'inline_run.dart';

/// An immutable block: stable id, type key, attribute bag, and ordered
/// inline runs.
///
/// The [id] is stable for the block's lifetime — edits never regenerate it
/// ([copyWith] deliberately has no `id` parameter). Block-based drag/move and
/// decoration sharding key on it.
final class Block {
  /// Creates a block.
  ///
  /// [attributes] is deep-frozen (see [freezeAttributes]); [runs] is copied
  /// into an unmodifiable list (a shallow copy — the runs themselves are
  /// shared).
  Block({
    required String id,
    required String type,
    Attributes attributes = emptyAttributes,
    List<InlineRun> runs = const <InlineRun>[],
  }) : this._(
          id,
          type,
          freezeAttributes(attributes),
          List<InlineRun>.unmodifiable(runs),
          _contentLengthOf(runs),
        );

  Block._(
    this.id,
    this.type,
    this.attributes,
    this.runs,
    this.contentLength,
  );

  /// Stable identity, never regenerated by edits.
  final String id;

  /// The block type key (e.g. `'paragraph'`); semantics live in consumers.
  final String type;

  /// The block's attribute bag (deep-frozen, JSON-compatible).
  ///
  /// Hosts consumer metadata untranslated — e.g. Nexus's `nexus` map.
  final Attributes attributes;

  /// Ordered inline content (unmodifiable list).
  final List<InlineRun> runs;

  /// Total number of characters across [runs] (cached at construction).
  final int contentLength;

  /// Token size of this block: [contentLength] plus the opening and closing
  /// tokens (empty block ⇒ size 2).
  int get size => contentLength + 2;

  /// The concatenated text of all runs.
  late final String text = runs.map((run) => run.text).join();

  /// Returns a block with the given fields replaced and the same [id].
  ///
  /// Untouched fields are shared by reference — omitting [attributes] reuses
  /// the frozen bag, omitting [runs] reuses the same run list. No deep copies
  /// happen anywhere.
  Block copyWith({
    String? type,
    Attributes? attributes,
    List<InlineRun>? runs,
  }) {
    return Block._(
      id,
      type ?? this.type,
      attributes == null ? this.attributes : freezeAttributes(attributes),
      runs == null ? this.runs : List<InlineRun>.unmodifiable(runs),
      runs == null ? contentLength : _contentLengthOf(runs),
    );
  }

  static int _contentLengthOf(List<InlineRun> runs) {
    var length = 0;
    for (final run in runs) {
      length += run.length;
    }
    return length;
  }

  @override
  String toString() => 'Block(#$id $type, ${runs.length} runs, size $size)';
}
